spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.routes[0].id=USERSERVICE
spring.cloud.gateway.routes[0].uri=http://localhost:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/user/**

spring.cloud.gateway.routes[1].id=PGMANAGMENT
spring.cloud.gateway.routes[1].uri=http://localhost:8083
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/rooms/**

spring.cloud.gateway.routes[2].id=BOOKINGSERVICE
spring.cloud.gateway.routes[2].uri=http://localhost:8084
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/bookings/**

spring.cloud.gateway.routes[3].id=USERSERVICE
spring.cloud.gateway.routes[3].uri=http://localhost:8082
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[4].id=USERSERVICE
spring.cloud.gateway.routes[4].uri=http://localhost:8082
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/admin/**

eureka.client.service-url.defaultZone=http://localhost:8763/eureka/